import re
from typing import Any, Dict, List, Optional

class FormulaValidator:
    """
    Validates Excel formulas generated by the Hybrid AI pipeline.
    Ensures:
    1. Whitelist check (strictly 18 defined formulas)
    2. Syntax validation (parentheses, quotes, prefix)
    3. Parameter count validation per formula spec
    4. Column existence in dataset schema
    5. Data type compatibility (numeric targets for math operations)
    6. Logical expressions in IF / IFS
    """

    SUPPORTED_FORMULAS = {
        "SUM", "SUMIF", "SUMIFS",
        "AVERAGE", "AVERAGEIF", "AVERAGEIFS",
        "COUNT", "COUNTA", "COUNTIF", "COUNTIFS",
        "MAX", "MIN", "MAXIFS", "MINIFS",
        "IF", "IFS",
        "VLOOKUP", "XLOOKUP",
        "INDEX", "MATCH",
        "FILTER"
    }

    NUMERIC_REQUIRING_FORMULAS = {
        "SUM", "SUMIF", "SUMIFS",
        "AVERAGE", "AVERAGEIF", "AVERAGEIFS",
        "MAX", "MIN", "MAXIFS", "MINIFS"
    }

    VALID_OPERATORS = {">", "<", ">=", "<=", "=", "<>", "!="}

    @classmethod
    def validate(
        cls,
        formula_str: str,
        target_column_info: Optional[Dict[str, Any]] = None,
        conditions_info: Optional[List[Dict[str, Any]]] = None,
        schema_columns: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Runs comprehensive validation on an Excel formula string.
        """
        errors = []
        warnings = []
        f_clean = formula_str.strip()

        # 1. Syntax: Must start with =
        if not f_clean.startswith("="):
            errors.append("Formula must start with '=' sign.")
            return cls._build_result(False, "syntax_error", errors, warnings, f_clean, "UNKNOWN")

        # 2. Extract Formula Name
        match_fn = re.match(r"^=([A-Za-z0-9_\.]+)\s*\(", f_clean)
        if not match_fn:
            errors.append("Invalid formula structure: Cannot extract function name.")
            return cls._build_result(False, "syntax_error", errors, warnings, f_clean, "UNKNOWN")

        formula_name = match_fn.group(1).upper()

        # 3. Whitelist check
        if formula_name not in cls.SUPPORTED_FORMULAS:
            errors.append(f"Formula '{formula_name}' is not in the whitelist of 18 supported formulas.")
            return cls._build_result(False, "unsupported_formula", errors, warnings, f_clean, formula_name)

        # 4. Balanced Parentheses
        open_parens = f_clean.count("(")
        close_parens = f_clean.count(")")
        if open_parens != close_parens:
            errors.append(f"Unbalanced parentheses: found {open_parens} '(' and {close_parens} ')'.")

        # 5. Balanced Quotes
        quote_count = f_clean.count('"')
        if quote_count % 2 != 0:
            errors.append(f"Unbalanced quotation marks: found {quote_count} '\"'.")

        # 6. Parse Top-Level Arguments
        inner_content = f_clean[len(formula_name) + 2 : -1].strip()
        args = cls._split_arguments(inner_content)

        # 7. Formula Specific Parameter Count Validation
        cls._validate_parameter_count(formula_name, args, errors, warnings)

        # 8. Target Column Data Type Validation
        if formula_name in cls.NUMERIC_REQUIRING_FORMULAS and target_column_info:
            inferred_type = (target_column_info.get("inferred_type") or target_column_info.get("data_type") or "").lower()
            if inferred_type in ["text", "categorical", "string"]:
                errors.append(f"Formula '{formula_name}' requires numeric target column, but received '{target_column_info.get('original_name', 'target')}' of type '{inferred_type}'.")

        # 9. Column Existence Check
        if schema_columns:
            cls._validate_columns_exist(args, schema_columns, warnings)

        # 10. Logical Expression Validation for IF/IFS
        if formula_name in ["IF", "IFS"]:
            cls._validate_logical_expression(formula_name, args, errors, warnings)

        is_valid = len(errors) == 0
        status = "valid" if is_valid else ("unsupported_formula" if formula_name not in cls.SUPPORTED_FORMULAS else "syntax_error")
        if not is_valid and any("numeric target" in e for e in errors):
            status = "type_mismatch"

        return cls._build_result(is_valid, status, errors, warnings, f_clean, formula_name)

    @classmethod
    def _split_arguments(cls, inner: str) -> List[str]:
        """Splits arguments by comma outside quotes and nested parentheses."""
        args = []
        current = []
        in_quotes = False
        depth = 0

        for char in inner:
            if char == '"':
                in_quotes = not in_quotes
                current.append(char)
            elif char == '(' and not in_quotes:
                depth += 1
                current.append(char)
            elif char == ')' and not in_quotes:
                depth -= 1
                current.append(char)
            elif char == ',' and depth == 0 and not in_quotes:
                args.append("".join(current).strip())
                current = []
            else:
                current.append(char)

        if current:
            args.append("".join(current).strip())

        return [a for a in args if a]

    @classmethod
    def _validate_parameter_count(
        cls, formula_name: str, args: List[str], errors: List[str], warnings: List[str]
    ):
        count = len(args)
        if formula_name in ["SUM", "AVERAGE", "COUNT", "COUNTA", "MAX", "MIN"]:
            if count < 1:
                errors.append(f"{formula_name} requires at least 1 parameter range, received {count}.")
        elif formula_name in ["SUMIF", "AVERAGEIF"]:
            if count not in [2, 3]:
                errors.append(f"{formula_name} requires 2 or 3 parameters (range, criteria, [sum_range]), received {count}.")
        elif formula_name in ["SUMIFS", "AVERAGEIFS", "MAXIFS", "MINIFS"]:
            if count < 3 or count % 2 == 0:
                errors.append(f"{formula_name} requires an odd number of parameters >= 3 (target_range, range1, crit1, ...), received {count}.")
        elif formula_name == "COUNTIF":
            if count != 2:
                errors.append(f"COUNTIF requires exactly 2 parameters (range, criteria), received {count}.")
        elif formula_name == "COUNTIFS":
            if count < 2 or count % 2 != 0:
                errors.append(f"COUNTIFS requires an even number of parameters >= 2 (range1, crit1, ...), received {count}.")
        elif formula_name == "IF":
            if count not in [2, 3]:
                errors.append(f"IF requires 2 or 3 parameters (logical_test, [value_if_true], [value_if_false]), received {count}.")
        elif formula_name == "IFS":
            if count < 2 or count % 2 != 0:
                errors.append(f"IFS requires paired condition/value parameters (even count >= 2), received {count}.")
        elif formula_name == "XLOOKUP":
            if count < 3:
                errors.append(f"XLOOKUP requires at least 3 parameters (lookup_val, lookup_array, return_array), received {count}.")
        elif formula_name == "VLOOKUP":
            if count not in [3, 4]:
                errors.append(f"VLOOKUP requires 3 or 4 parameters (lookup_val, table_array, col_index, [range_lookup]), received {count}.")
        elif formula_name == "MATCH":
            if count not in [2, 3]:
                errors.append(f"MATCH requires 2 or 3 parameters, received {count}.")
        elif formula_name == "FILTER":
            if count < 2:
                errors.append(f"FILTER requires at least 2 parameters (array, include), received {count}.")
        elif formula_name == "INDEX":
            if count < 1 or count > 3:
                errors.append(f"INDEX requires 1, 2, or 3 parameters, received {count}.")

    @classmethod
    def _validate_columns_exist(cls, args: List[str], schema_columns: List[str], warnings: List[str]):
        """Checks if structured references Table[Col] exist in schema."""
        for arg in args:
            table_match = re.search(r"\[([^\]]+)\]", arg)
            if table_match:
                col_name = table_match.group(1)
                if not any(c.lower() == col_name.lower() for c in schema_columns):
                    warnings.append(f"Referenced column '{col_name}' was not found in active dataset columns.")

    @classmethod
    def _validate_logical_expression(
        cls, formula_name: str, args: List[str], errors: List[str], warnings: List[str]
    ):
        """Validates logical comparisons inside IF / IFS."""
        if formula_name == "IF" and args:
            test_expr = args[0]
            if not any(op in test_expr for op in cls.VALID_OPERATORS) and test_expr.upper() != "TRUE":
                warnings.append(f"Logical condition '{test_expr}' does not contain a standard comparison operator.")
        elif formula_name == "IFS":
            # Odd index parameters are logical conditions (0, 2, 4...)
            for idx in range(0, len(args), 2):
                cond = args[idx]
                if cond.upper() != "TRUE" and not any(op in cond for op in cls.VALID_OPERATORS):
                    warnings.append(f"IFS condition at position {idx+1} ('{cond}') lacks a standard comparison operator.")

    @classmethod
    def _build_result(
        cls, is_valid: bool, status: str, errors: List[str], warnings: List[str], formula: str, formula_name: str
    ) -> Dict[str, Any]:
        return {
            "is_valid": is_valid,
            "status": status,
            "formula": formula,
            "formula_name": formula_name,
            "errors": errors,
            "warnings": warnings
        }
